services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    volumes:
      - ./client/src:/app/src
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./api/src:/app/src
    env_file:
      - ./api/dev.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./api/dev.env
    ports:
      - "5432:5432"
