services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.test
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    volumes:
      - ./client/__tests__:/app/__tests__
      - ./client/src:/app/src
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    ports:
      - "80:80"
    volumes:
      - ./api/src:/app/src
      - ./api/__tests__:/app/__tests__
      - ./api/vitest.config.ts:/app/vitest.config.ts
      - ./api/vitest.setup.ts:/app/vitest.setup.ts
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
      - POSTGRES_DB=pikoria_test
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_DB=pikoria_test
    ports:
      - "5432:5432"
